### ISSUE TITLE
Provide a way to edit the session before uploading

### ISSUE THREAD

**Issue by ghost** [ConradIrwin/showterm#11]
Editing the session before it's uploaded would allow me to fix y^Htypos and accidental passwords.

**Comment by marvinpinto** [comment]
For anyone else that lands here searching for how to edit a session before uploading, I found it slightly confusing at first so I [wrote up](https://disjoint.ca/til/2017/09/17/create-a-screencast-of-your-terminal-session-using-showterm) how I did it. Hopefully this is helpful to someone else.

**Comment by ConradIrwin** [comment]
Nice hack, thanks Marvin!

Sent via Superhuman ( https://sprh.mn/?vip=conrad@superhuman.com )
