### ISSUE TITLE
deleting a recording

### ISSUE THREAD

**Issue by sameer-pradhan** [ConradIrwin/showterm#35]
Is there any way to remove the recording?

**Comment by ConradIrwin** [comment]
Run `showterm --delete url` from the same computer you recorded it.

**Comment by sameer-pradhan** [comment]
> On May 27, 2015, at 4:58 PM, Conrad Irwin <notifications@github.com> wrote:
> 
> Run showterm --delete url from the same computer you recorded it.

cool! thanks!

-- sameer
