### ISSUE TITLE
option to NOT record the ending "exit" command in the video?

### ISSUE THREAD

**Issue by baijianpeng** [ConradIrwin/showterm#41]
I started recording with purely "showterm" command, without any other parameters.

When finishing the recording, I need to input the "exit" command.

However, when playing the recorded video, I noticed that my final "exit" command and its response "ex" ( first two letters of the screen output "exit") were ALL recorded.

I think this final "exit" command should NOT be recorded, since it is not part of my screen capture content, it is only a command to stop/end the recording operation.

If it is not easy to hide this final "exit" command, maybe you can consider to use keyboard combination to stop/end the recording to avoid this.

Thank you.

**Comment by ConradIrwin** [comment]
You can use ctrl+D for this.
