### ISSUE TITLE
https://showterm.io/ is down

### ISSUE THREAD

**Issue by DmytroRublov** [ConradIrwin/showterm#44]
Hello Conrad,

Looks like https://showterm.io/ website is down currently:
I'm getting "Application error" when I open it in a browser.
If you can, please take a look.
Thank you.

**Comment by ConradIrwin** [comment]
Fixed! I just ran out of Heroku credit, sorry about that

P.S. Superhuman is hiring iOS engineers — k now anyone? $1947 referral bonus. Learn more ( https://superhuman.com/jobs ). 

Sent via Superhuman ( https://sprh.mn/?vip=conrad@superhuman.com )

**Comment by DmytroRublov** [comment]
Thank you, Conrad! 👍 
Sorry, don't know any iOS engineers :(
