### ISSUE TITLE
GIF?

### ISSUE THREAD

**Issue by Nakilon** [ConradIrwin/showterm#50]
How does this work? Where and how it stores the file on my machine? I would like to know it to be able to convert to GIF and upload eslewhere instead of using the proposed website.

**Comment by KawaCoder** [comment]
Hey! When you record your terminal using showterm -e (to save files) with two file are created, one named as showtime.xxxx.script, that define what is written in the terminal, and one named as showtime.xxxx.times, that define the timeline of the written script. You can use `showterm --retry "/tmp/showtime.7851.script" "/tmp/showtime.7851.times"
` to upload these files, after modifying them. But it is not an image format, it is pure text. But if you want to export it somewhere else, you can use the badge i created: 

-Markdown:
`[![hey](https://img.shields.io/badge/Run%20the%20online%20demo-181717?style=for-the-badge&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAArlBMVEUAAAAAzP8Aov8Aov8AqP8Aof8Ao/8Aov8AoP8ApP8Aov8AoP8Ao/8Ao/8An/8AoP8Aof8Aov8Aof8Aov8Aov8AluwAoP8Aof8AoP8Aof8Aof8AiNcAoP8Aov8Aof8Aov8Aof8Aov8Aof8Aof8Aof8AoP8Aof8AoP4AoP8AoP8Aof8Aof8Aov8Aof4AmvcAlO0AlvAAh9cAidoAitwAjN4Aj+MAkOYAkugAk+v///+P6XhkAAAAMXRSTlMABQshKS4vNzs7PEZLXmBhgIONjpaXn6Okpqiur7CxsrO1tri5ur7BwszO0djb5Oj45w0EeQAAAF9JREFUeNqtwoO1wwAAAMD7Zu02tc1g/8XqEXLvpGPsqZgRvLHahz/uYh87ssea3//khXrDLI/ToeNriege800Pyn2jCnLBYj34S15FJPDe3bZ9DhWmmlV3E1D61pKSC9reBzUZeaVSAAAAAElFTkSuQmCC&color=000000)](<--LINK OF THE SHOWTERM -->)`

And it looks like this:
[![hey](https://img.shields.io/badge/Run%20the%20online%20demo-181717?style=for-the-badge&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAArlBMVEUAAAAAzP8Aov8Aov8AqP8Aof8Ao/8Aov8AoP8ApP8Aov8AoP8Ao/8Ao/8An/8AoP8Aof8Aov8Aof8Aov8Aov8AluwAoP8Aof8AoP8Aof8Aof8AiNcAoP8Aov8Aof8Aov8Aof8Aov8Aof8Aof8Aof8AoP8Aof8AoP4AoP8AoP8Aof8Aof8Aov8Aof4AmvcAlO0AlvAAh9cAidoAitwAjN4Aj+MAkOYAkugAk+v///+P6XhkAAAAMXRSTlMABQshKS4vNzs7PEZLXmBhgIONjpaXn6Okpqiur7CxsrO1tri5ur7BwszO0djb5Oj45w0EeQAAAF9JREFUeNqtwoO1wwAAAMD7Zu02tc1g/8XqEXLvpGPsqZgRvLHahz/uYh87ssea3//khXrDLI/ToeNriege800Pyn2jCnLBYj34S15FJPDe3bZ9DhWmmlV3E1D61pKSC9reBzUZeaVSAAAAAElFTkSuQmCC&color=000000)](http://showterm.io/8b1589bcb96e72d3a58dc#fast)

**Comment by Nakilon** [comment]
Neither I see the GIF nor how your link is different from  showterm website.

**Comment by ConradIrwin** [comment]
@DR34M-M4K3R Nice badge, thank you!

@Nakilon Showterm does not support making a video or a gif (as @DR34M-M4K3R said, Showterm uses text files instead). I would recommend you use a screen recorder instead. On Mac OS to create a gif I use https://www.cockos.com/licecap/ and to create a video I use Quicktime (which is built in).
